server:
  port: 8082

spring:
  application:
    name: DormServer
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dorm?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 100
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000
  # data:
  #   redis:
  #     host: 
  #     port: 6379
  #     database: 1
  #     password: 
  #     timeout: 3000ms
  #     lettuce:
  #       pool:
  #         max-active: 8  # 最大连接数，负值表示没有限制，默认8
  #         max-wait: -1    # 最大阻塞等待时间，负值表示没限制，默认-1
  #         max-idle: 8     # 最大空闲连接，默认8
  #         min-idle: 1
  profiles:
    active: dev
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kaiyu.domain.entity
  type-aliases-super-type: java.lang.Object
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

oss:
  local:
    bucket: /software/diancan/img/
    read-path: ''
    enable: true

logging:
  config: classpath:logback-spring.xml